/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package sistemapasajes.View;

import com.google.gson.Gson;
import com.google.gson.JsonElement;
import java.awt.Dimension;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import sistemapasajes.ArchivosPlanos;
import sistemapasajes.Funciones;
import sistemapasajes.dao.ApiDAO;
import sistemapasajes.dao.ApiDAOImpl;
import sistemapasajes.dao.ComprobanteDAO;
import sistemapasajes.dao.ComprobanteDAOImpl;
import sistemapasajes.dao.ConfiguracionDAO;
import sistemapasajes.dao.ConfiguracionDAOImpl;
import sistemapasajes.dao.DcomprobanteDAO;
import sistemapasajes.dao.DcomprobanteDAOImpl;
import sistemapasajes.dao.EmpresaDAO;
import sistemapasajes.dao.EmpresaDAOImpl;
import sistemapasajes.dao.EncomiendaDAO;
import sistemapasajes.dao.EncomiendaDAOImpl;
import sistemapasajes.dao.PasajeroDAO;
import sistemapasajes.dao.PasajeroDAOimpl;
import sistemapasajes.modelo.PasajeroModel;
import sistemapasajes.dao.SerieDAO;
import sistemapasajes.dao.SerieDAOImpl;
import sistemapasajes.modelo.ComprobanteModel;
import sistemapasajes.modelo.ConfiguracionModel;
import sistemapasajes.modelo.DcomprobanteModel;
import sistemapasajes.modelo.EmpresaModel;
import sistemapasajes.modelo.EncomiendaModel;
import sistemapasajes.modelo.SerieModel;

/**
 *
 * @author Edson Cusicuna
 */
public class Encomienda extends javax.swing.JInternalFrame {

    /**
     * Creates new form Encomienda
     */
    int numero;
    String numserie;
    String codserie;
    String codsunatserie;
    String rutasunat;
    String rucempresa;
    String tipocompsunat;
    String tipdoccli;
    ConfiguracionDAO configuraciondao = new ConfiguracionDAOImpl();
    ConfiguracionModel configuracion = new ConfiguracionModel();
    String json;
    ApiDAO apidao = new ApiDAOImpl();
    String tiposerie;

    public Encomienda() {
        initComponents();
        configuracion = configuraciondao.obtenerConfiguracionPorId(1);

        SerieDAO seriedao = new SerieDAOImpl();
        SerieModel serie = seriedao.obtenerTipoSerie("BOLETA", "B001");
        numero = serie.getNumSerie() + 1;
        codserie = serie.getCodSerie();
        numserie = codserie + "-" + numero;
        String tiposerie = serie.getTipoSerie();
        Date hoy = new Date();
        txtcomprobante.setText(numserie);
        txttipocomprobante.setText(tiposerie);

        cbunidad.removeAllItems();
        cbunidad.addItem("Seleccionar");
        cbunidad.addItem("UNIDAD");
        cbunidad.addItem("PAQUETE");
        cbunidad.addItem("CAJA");
        cbunidad.addItem("BOLSA");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        chkbfactura = new javax.swing.JCheckBox();
        jLabel10 = new javax.swing.JLabel();
        txtcomprobante = new javax.swing.JTextField();
        txttipocomprobante = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtdni = new javax.swing.JTextField();
        btnbpersona = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtpasajero = new javax.swing.JTextField();
        btnnpasajero = new javax.swing.JButton();
        pnlfactura = new javax.swing.JPanel();
        txtruc = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        btnbempresa = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        txtrazon = new javax.swing.JTextField();
        txtdireccion = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        btnnempresa = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtorigen = new javax.swing.JTextField();
        txtdestino = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtdescenco = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtcantidadenco = new javax.swing.JTextField();
        cbunidad = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        btnnpasajero1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabenco = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        txtprecio = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        btncomprobante = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txtdni1 = new javax.swing.JTextField();
        btnbpersona1 = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        txtpasajero1 = new javax.swing.JTextField();
        btnnpasajero2 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        setClosable(true);
        setIconifiable(true);
        setTitle("Encomienda");

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos del Comprobante", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N

        chkbfactura.setBackground(new java.awt.Color(255, 255, 255));
        chkbfactura.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        chkbfactura.setText("Requiere Factura");
        chkbfactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkbfacturaActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setText("N° de Comprobante:");

        txtcomprobante.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtcomprobante.setEnabled(false);

        txttipocomprobante.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txttipocomprobante.setEnabled(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chkbfactura)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtcomprobante, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txttipocomprobante, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtcomprobante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txttipocomprobante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chkbfactura))
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos Remitente", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("DNI:");

        txtdni.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        btnbpersona.setBackground(new java.awt.Color(45, 85, 195));
        btnbpersona.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnbpersona.setForeground(new java.awt.Color(255, 255, 255));
        btnbpersona.setText("Buscar");
        btnbpersona.setBorder(null);
        btnbpersona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbpersonaActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Datos:");

        txtpasajero.setEditable(false);
        txtpasajero.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        btnnpasajero.setBackground(new java.awt.Color(40, 150, 180));
        btnnpasajero.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnnpasajero.setForeground(new java.awt.Color(255, 255, 255));
        btnnpasajero.setText("Nuevo");
        btnnpasajero.setBorder(null);
        btnnpasajero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnpasajeroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtdni, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnbpersona, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtpasajero, javax.swing.GroupLayout.PREFERRED_SIZE, 483, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnnpasajero, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(txtpasajero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnnpasajero, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(txtdni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnbpersona, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlfactura.setBackground(new java.awt.Color(255, 255, 255));
        pnlfactura.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos de Facturación", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N
        pnlfactura.setEnabled(false);
        pnlfactura.setName(""); // NOI18N

        txtruc.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtruc.setEnabled(false);

        jLabel11.setText("RUC:");

        btnbempresa.setBackground(new java.awt.Color(45, 85, 195));
        btnbempresa.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnbempresa.setForeground(new java.awt.Color(255, 255, 255));
        btnbempresa.setText("Buscar");
        btnbempresa.setBorder(null);
        btnbempresa.setEnabled(false);
        btnbempresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbempresaActionPerformed(evt);
            }
        });

        jLabel12.setText("Datos:");

        txtrazon.setEditable(false);
        txtrazon.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        txtdireccion.setEditable(false);
        txtdireccion.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel13.setText("Dirección:");

        btnnempresa.setBackground(new java.awt.Color(40, 150, 180));
        btnnempresa.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnnempresa.setForeground(new java.awt.Color(255, 255, 255));
        btnnempresa.setText("Nuevo");
        btnnempresa.setBorder(null);
        btnnempresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnempresaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlfacturaLayout = new javax.swing.GroupLayout(pnlfactura);
        pnlfactura.setLayout(pnlfacturaLayout);
        pnlfacturaLayout.setHorizontalGroup(
            pnlfacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlfacturaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlfacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlfacturaLayout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtruc, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnbempresa, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtrazon))
                    .addGroup(pnlfacturaLayout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtdireccion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnnempresa, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        pnlfacturaLayout.setVerticalGroup(
            pnlfacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlfacturaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlfacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtruc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(btnbempresa, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(txtrazon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlfacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txtdireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnnempresa, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos Encomienda", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N

        jDateChooser1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Fecha");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("Origen:");

        txtorigen.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtorigen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtorigenActionPerformed(evt);
            }
        });

        txtdestino.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("Destino:");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel14.setText("Descripción:");

        txtdescenco.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtdescenco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdescencoActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel15.setText("Cantidad:");

        txtcantidadenco.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtcantidadenco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcantidadencoActionPerformed(evt);
            }
        });

        cbunidad.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbunidad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel16.setText("Unidad:");

        btnnpasajero1.setBackground(new java.awt.Color(40, 150, 180));
        btnnpasajero1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnnpasajero1.setForeground(new java.awt.Color(255, 255, 255));
        btnnpasajero1.setText("Agregar");
        btnnpasajero1.setBorder(null);
        btnnpasajero1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnpasajero1ActionPerformed(evt);
            }
        });

        tabenco.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Descripcion", "Unidad", "Cantidad", "Precio"
            }
        ));
        jScrollPane1.setViewportView(tabenco);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Precio: S/");

        txtprecio.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Soles");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtorigen, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtdescenco)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel16))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(txtdestino, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtprecio, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(cbunidad, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtcantidadenco, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(btnnpasajero1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(13, 13, 13))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtprecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txtorigen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addComponent(txtdestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1)
                        .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(txtdescenco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(txtcantidadenco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbunidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16)
                    .addComponent(btnnpasajero1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        btncomprobante.setBackground(new java.awt.Color(30, 200, 130));
        btncomprobante.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btncomprobante.setForeground(new java.awt.Color(255, 255, 255));
        btncomprobante.setText("Generar Comprobante");
        btncomprobante.setBorder(null);
        btncomprobante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncomprobanteActionPerformed(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos Destinatario", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("DNI:");

        txtdni1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        btnbpersona1.setBackground(new java.awt.Color(45, 85, 195));
        btnbpersona1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnbpersona1.setForeground(new java.awt.Color(255, 255, 255));
        btnbpersona1.setText("Buscar");
        btnbpersona1.setBorder(null);
        btnbpersona1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbpersona1ActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel17.setText("Datos:");

        txtpasajero1.setEditable(false);
        txtpasajero1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        btnnpasajero2.setBackground(new java.awt.Color(40, 150, 180));
        btnnpasajero2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnnpasajero2.setForeground(new java.awt.Color(255, 255, 255));
        btnnpasajero2.setText("Nuevo");
        btnnpasajero2.setBorder(null);
        btnnpasajero2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnpasajero2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtdni1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnbpersona1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtpasajero1, javax.swing.GroupLayout.PREFERRED_SIZE, 483, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnnpasajero2, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel17)
                        .addComponent(txtpasajero1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnnpasajero2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(txtdni1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnbpersona1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlfactura, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btncomprobante, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlfactura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btncomprobante, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void chkbfacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkbfacturaActionPerformed
        SerieDAO seriedao = new SerieDAOImpl();
        SerieModel serie;

        if (chkbfactura.isSelected()) {
            serie = seriedao.obtenerTipoSerie("FACTURA", "F001");
            numero = serie.getNumSerie() + 1;
            codserie = serie.getCodSerie();
            numserie = codserie + "-" + numero;
            codsunatserie = serie.getCodsunatSerie();
            tiposerie = serie.getTipoSerie();
            System.out.println("holis");
            pnlfactura.setEnabled(true);
            txtruc.setEnabled(true);
            btnbempresa.setEnabled(true);
            tipdoccli = "6";
        } else {
            serie = seriedao.obtenerTipoSerie("BOLETA", "B001");
            numero = serie.getNumSerie() + 1;
            codserie = serie.getCodSerie();
            numserie = codserie + "-" + numero;
            codsunatserie = serie.getCodsunatSerie();
            tiposerie = serie.getTipoSerie();
            System.out.println("adios");
            pnlfactura.setEnabled(false);
            txtruc.setEnabled(false);
            btnbempresa.setEnabled(false);
            tipdoccli = "1";
        }
        txtcomprobante.setText(numserie);
        txttipocomprobante.setText(tiposerie);
    }//GEN-LAST:event_chkbfacturaActionPerformed

    private void btnbpersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbpersonaActionPerformed

        String dni = txtdni.getText().trim();
        //CONSULTAR A API PARA PODER REGISTRARLO
        String url = null;// Obtener el texto y eliminar espacios en blanco

        if (!dni.isEmpty()) { // Verificar si el texto no está vacío
            PasajeroDAO pasajerodao = new PasajeroDAOimpl();
            PasajeroModel pasajero = pasajerodao.obtenerPasajeroPorDNI(dni);
            PasajeroModel psjemodel = new PasajeroModel();

            if (pasajero != null) {
                int pasajero_existe = pasajero.getIdPsje();
                System.out.println(pasajero_existe);
                txtpasajero.setText(pasajero.getApePsje() + " " + pasajero.getNomPsje());
            } else {
                // No se encontró el pasajero, muestra un JOptionPane
                JOptionPane.showMessageDialog(null, "Pasajero no se encuentra en la Base de Datos Interna, se realizará una consulta externa. \n Espere por favor.", "Información", JOptionPane.INFORMATION_MESSAGE);

                //CONSULTAR A API PARA PODER REGISTRARLO
                url = apidao.obtenerApiPorId(1).getUrlApi() + dni;
                try {
                    Funciones.realizarConsultaApi(url);
                    json = Funciones.realizarConsultaApi(url);
                } catch (IOException ex) {
                    Logger.getLogger(Pasajes.class.getName()).log(Level.SEVERE, null, ex);
                }
                try {
                    System.out.println(Funciones.realizarConsultaApi(url));

                    // Crear un objeto Gson
                    Gson gson = new Gson();

                    // Analizar el JSON y convertirlo en un objeto JsonElement
                    JsonElement jsonElement = gson.fromJson(json, JsonElement.class);

                    // Obtener los valores deseados del JsonElement
                    String nombrecompleto = jsonElement.getAsJsonObject().get("nombre").getAsString();
                    String nombres = jsonElement.getAsJsonObject().get("nombres").getAsString();
                    String apellidos = jsonElement.getAsJsonObject().get("apellidoPaterno").getAsString() + " " + jsonElement.getAsJsonObject().get("apellidoMaterno").getAsString();
                    String numdoc = jsonElement.getAsJsonObject().get("numeroDocumento").getAsString();

                    txtpasajero.setText(nombrecompleto);
                    psjemodel.setNumdocPsje(numdoc);
                    psjemodel.setNomPsje(nombres);
                    psjemodel.setApePsje(apellidos);

                    //AGREGAR PERSONA
                    pasajerodao.agregarPasajero(psjemodel);

                } catch (IOException ex) {
                    Logger.getLogger(Pasajes.class.getName()).log(Level.SEVERE, null, ex);
                }
            }

            System.out.println(url);
        } else {
            JOptionPane.showMessageDialog(null, "Ingrese un DNI de pasajero válido antes de consultar.", "ADVERTENCIA", JOptionPane.INFORMATION_MESSAGE);
            System.out.println("Ingrese un DNI de pasajero válido antes de consultar.");
        }
    }//GEN-LAST:event_btnbpersonaActionPerformed

    private void btnnpasajeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnpasajeroActionPerformed
        JInternalFrame internalFrame = new Pasajero();

        Principal.jDesktopPane1.add(internalFrame);
        // Calcular la posición para centrar el JInternalFrame
        Dimension desktopSize = Principal.jDesktopPane1.getSize();
        Dimension jInternalFrameSize = internalFrame.getSize();

        int posX = (desktopSize.width - jInternalFrameSize.width) / 2;
        int posY = (desktopSize.height - jInternalFrameSize.height) / 2;

        // Establecer la ubicación centrada
        internalFrame.setLocation(posX, posY);

        internalFrame.setVisible(true);
    }//GEN-LAST:event_btnnpasajeroActionPerformed

    private void btnbempresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbempresaActionPerformed

        String ruc = txtruc.getText().trim();
        //CONSULTAR A API PARA PODER REGISTRARLO
        String url = null;// Obtener el texto y eliminar espacios en blanco

        if (!ruc.isEmpty()) { // Verificar si el texto no está vacío
            EmpresaDAO empresadao = new EmpresaDAOImpl();
            EmpresaModel empresa = empresadao.obtenerEmpresaporRuc(ruc);
            EmpresaModel empresamodel = new EmpresaModel();

            if (empresa != null) {
                int empresa_existe = empresa.getIdEmp();
                System.out.println(empresa_existe);
                txtrazon.setText(empresa.getRazonEmp());
                txtdireccion.setText(empresa.getDireccionEmp());
            } else {
                // No se encontró el pasajero, muestra un JOptionPane
                JOptionPane.showMessageDialog(null, "Empresa no se encuentra en la Base de Datos Interna, se realizará una consulta externa. \n Espere por favor.", "Información", JOptionPane.INFORMATION_MESSAGE);

                //CONSULTAR A API PARA PODER REGISTRARLO
                url = apidao.obtenerApiPorId(2).getUrlApi() + ruc;
                try {
                    Funciones.realizarConsultaApi(url);
                    json = Funciones.realizarConsultaApi(url);
                } catch (IOException ex) {
                    Logger.getLogger(Pasajes.class.getName()).log(Level.SEVERE, null, ex);
                }
                try {
                    System.out.println(Funciones.realizarConsultaApi(url));

                    // Crear un objeto Gson
                    Gson gson = new Gson();

                    // Analizar el JSON y convertirlo en un objeto JsonElement
                    JsonElement jsonElement = gson.fromJson(json, JsonElement.class);

                    // Obtener los valores deseados del JsonElement
                    String nombrecompleto = jsonElement.getAsJsonObject().get("nombre").getAsString();
                    String tipodocumento = jsonElement.getAsJsonObject().get("tipoDocumento").getAsString();
                    String numdoc = jsonElement.getAsJsonObject().get("numeroDocumento").getAsString();
                    String direccion = jsonElement.getAsJsonObject().get("direccion").getAsString() + " " + jsonElement.getAsJsonObject().get("distrito").getAsString()
                            + " " + jsonElement.getAsJsonObject().get("provincia").getAsString() + " " + jsonElement.getAsJsonObject().get("departamento").getAsString();
                    String ubigeo = jsonElement.getAsJsonObject().get("ubigeo").getAsString();
                    String distrito = jsonElement.getAsJsonObject().get("distrito").getAsString();
                    String provincia = jsonElement.getAsJsonObject().get("provincia").getAsString();
                    String departamento = jsonElement.getAsJsonObject().get("departamento").getAsString();

                    txtrazon.setText(nombrecompleto);
                    txtdireccion.setText(direccion);

                    empresamodel.setTipodocEmp(tipodocumento);
                    empresamodel.setNumdocEmp(numdoc);
                    empresamodel.setRazonEmp(nombrecompleto);
                    empresamodel.setDireccionEmp(direccion);
                    empresamodel.setUbigeoEmp(ubigeo);
                    empresamodel.setDistritoEmp(distrito);
                    empresamodel.setProvinciaEmp(provincia);
                    empresamodel.setDepartamentoEmp(departamento);
                    empresadao.agregarEmpresa(empresamodel);

                } catch (IOException ex) {
                    Logger.getLogger(Pasajes.class.getName()).log(Level.SEVERE, null, ex);
                }
            }

            System.out.println(url);
        } else {
            JOptionPane.showMessageDialog(null, "Ingrese un RUC válido antes de consultar.", "ADVERTENCIA", JOptionPane.INFORMATION_MESSAGE);
            System.out.println("Ingrese un DNI de pasajero válido antes de consultar.");
        }
    }//GEN-LAST:event_btnbempresaActionPerformed

    private void btnnempresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnempresaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnnempresaActionPerformed

    private void txtorigenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtorigenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtorigenActionPerformed

    private void txtdescencoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdescencoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdescencoActionPerformed

    private void txtcantidadencoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcantidadencoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcantidadencoActionPerformed

    private void btnnpasajero1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnpasajero1ActionPerformed
        // Obtener los valores de los JTextField y JComboBox
        String origen = txtorigen.getText();
        String destino = txtdestino.getText();
        double precio = Double.parseDouble(txtprecio.getText());
        String descripcion = txtdescenco.getText();
        int cantidad = Integer.parseInt(txtcantidadenco.getText());
        String unidad = (String) cbunidad.getSelectedItem();

        // Crear un modelo de tabla para la JTable si aún no tiene uno
        DefaultTableModel modelo = (DefaultTableModel) tabenco.getModel();

        // Agregar los valores a la tabla
        modelo.addRow(new Object[]{descripcion, cantidad, unidad, precio});
        limpiarCamposTexto(txtprecio, txtcantidadenco, txtdescenco);
    }//GEN-LAST:event_btnnpasajero1ActionPerformed

    private void btncomprobanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncomprobanteActionPerformed

    if (!"".equals(txtdni.getText()) && jDateChooser1.getDate() != null
            && (chkbfactura.isSelected() ? !"".equals(txtrazon.getText()) : !"".equals(txtpasajero.getText()))
            && (chkbfactura.isSelected() ? !"".equals(txtruc.getText()) : !"".equals(txtdni.getText()))
            && !"".equals(txtorigen.getText()) && !"".equals(txtdestino.getText())) {

        try {
            //ARCHIVOS PLANOS
            ArchivosPlanos archivos = new ArchivosPlanos();

            ComprobanteDAO comprobantedao = new ComprobanteDAOImpl();
            DcomprobanteDAO dcomprobantedao = new DcomprobanteDAOImpl();
            EncomiendaDAO encomiendadao = new EncomiendaDAOImpl();

            // Obtener datos del formulario
            String tipo = txttipocomprobante.getText();
            String serie = txtcomprobante.getText();
            String cliente = chkbfactura.isSelected() ? txtrazon.getText() : txtpasajero.getText();
            String docliente = chkbfactura.isSelected() ? txtruc.getText() : txtdni.getText();

            Date fecha = jDateChooser1.getDate();
            String fechaformato = Funciones.convertirFecha(fecha);

            Date hora = new Date();
            SimpleDateFormat horaFormato = new SimpleDateFormat("HH:mm:ss");

            String horatexto = horaFormato.format(hora);

            String moneda = "PEN";
            String medio = "Contado";

            // Calcular el total del comprobante
            double total = 0.0;
            DefaultTableModel modeloTabla = (DefaultTableModel) tabenco.getModel();
            for (int i = 0; i < modeloTabla.getRowCount(); i++) {
                double preciofila = (double) modeloTabla.getValueAt(i, 3);
                total += preciofila;
            }

            double igv = total * 0.18;
            double totalgrav = total - igv;

            String fechaformato1 = Funciones.convertirFecha(fecha);
            String fechaformato2 = Funciones.convertirFecha(fecha);

            String estado = "XML NO GENERADO";

            String codtipo = null;
            if ("BOLETA".equals(tipo)) {
                codtipo = "03";
            } else if ("FACTURA".equals(tipo)) {
                codtipo = "01";
            }

            // Crear comprobante
            ComprobanteModel comprobante = new ComprobanteModel();
            comprobante.setTipoComp(codtipo);
            comprobante.setSerieComp(serie);
            comprobante.setDocclienteComp(docliente);
            comprobante.setClienteComp(cliente);
            comprobante.setFechaComp(fechaformato);
            comprobante.setMonedaComp(moneda);
            comprobante.setMediopagoComp(medio);
            comprobante.setTotalventgravComp(totalgrav);
            comprobante.setIgvComp(igv);
            comprobante.setImptotalComp(total);
            comprobante.setFechaxmlComp(fechaformato1);
            comprobante.setFechaenvioComp(fechaformato2);
            comprobante.setEstadoComp(estado);
            comprobante.setHoraComp(horatexto);
            comprobante.setAfecComp("AFECTO");

            comprobantedao.agregarComprobante(comprobante);

            // Crear detalle del comprobante
            int idcomprobante = comprobantedao.obtenerComprobanteporNum(serie).getIdComp();
            for (int i = 0; i < modeloTabla.getRowCount(); i++) {
                double preciofila = (double) modeloTabla.getValueAt(i, 3);
                double sinigvfila = preciofila - (preciofila * 0.18);
                int num = i + 1;
                DcomprobanteModel dcomprobante = new DcomprobanteModel();
                dcomprobante.setNumserieDcomp(serie);
                dcomprobante.setItemDcomp(i + 1);
                dcomprobante.setCantidadDcomp(1);
                dcomprobante.setTipunidDcomp("ZZ");
                dcomprobante.setProductoDcomp("EN00" + num);
                dcomprobante.setDescripcionDcomp("ENVIO DE: " + (String) modeloTabla.getValueAt(i, 2) + " DE " + (String) modeloTabla.getValueAt(i, 0));
                dcomprobante.setValorunitarioDcomp(sinigvfila);
                dcomprobante.setPreciounitarioDcomp(preciofila);
                dcomprobantedao.agregarDcomprobante(dcomprobante);

                // Crear encomienda
                EncomiendaModel encomienda = new EncomiendaModel();
                encomienda.setFechaEnco(fechaformato);
                encomienda.setDescEnco((String) modeloTabla.getValueAt(i, 0));
                encomienda.setUnidadEnco((String) modeloTabla.getValueAt(i, 2));
                encomienda.setCantidadEnco((Integer) modeloTabla.getValueAt(i, 1));
                encomienda.setOrigenEnco(txtorigen.getText());
                encomienda.setDestinoEnco(txtdestino.getText());
                encomienda.setPrecioEnco((double) modeloTabla.getValueAt(i, 3));
                encomienda.setComprobanteEnco(idcomprobante);
                encomienda.setDocremiEnco(txtdni.getText());
                encomienda.setRemiEnco(txtpasajero.getText());
                encomienda.setDocdestEnco(txtdni1.getText());
                encomienda.setDestiEnco(txtpasajero1.getText());
                encomiendadao.agregarEncomienda(encomienda);
            }

            // Actualizar número de serie
            SerieDAO seriedao = new SerieDAOImpl();
            SerieModel seriemodel = new SerieModel();
            seriemodel.setCodSerie(codserie);
            seriemodel.setNumSerie(numero);
            seriedao.actualizarNumSerie(seriemodel);

            //SE VUELVE A LLAMAR A LOS DATOS RECIEN INGRESADOS PARA GENERAR LOS ARCHIVOS PLANOS
            ComprobanteModel obtenerComprobante = comprobantedao.obtenerComprobanteporNum(numserie);
            DcomprobanteModel obtenerDcomprobante = dcomprobantedao.obtenerDcomprobanteporNum(numserie);

            tipocompsunat = seriedao.obtenerTipoSerie(tipo, codserie).getCodsunatSerie();

            //CREACIÓN ARCHIVOS PLANOS
            archivos.ArchivoPlanoCAB(configuracion, tipocompsunat, tipdoccli, obtenerComprobante);
            archivos.ArchivoPlanoDET(configuracion, tipocompsunat, obtenerDcomprobante, obtenerComprobante);
            archivos.ArchivoPlanoTRI(configuracion, tipocompsunat, obtenerComprobante);
            archivos.ArchivoPlanoLEY(configuracion, tipocompsunat, obtenerComprobante);
            archivos.ArchivoPlanoACA(configuracion, tipocompsunat, obtenerComprobante);
            archivos.ArchivoPlanoPAG(configuracion, tipocompsunat, obtenerComprobante);
            JOptionPane.showMessageDialog(null, "Archivos Planos Generados Correctamente", "Información", JOptionPane.INFORMATION_MESSAGE);

            this.dispose();

            JInternalFrame internalFrame = new Encomienda();

            Principal.jDesktopPane1.add(internalFrame);
            // Calcular la posición para centrar el JInternalFrame
            Dimension desktopSize = Principal.jDesktopPane1.getSize();
            Dimension jInternalFrameSize = internalFrame.getSize();

            int posX = (desktopSize.width - jInternalFrameSize.width) / 2;
            int posY = (desktopSize.height - jInternalFrameSize.height) / 2;

            // Establecer la ubicación centrada
            internalFrame.setLocation(posX, posY);

            internalFrame.setVisible(true);

        } catch (Exception ex) {
            gestionarExcepcion(ex);
        }
    } else {
        JOptionPane.showMessageDialog(null, "Existe Campos Vacíos", "Información", JOptionPane.INFORMATION_MESSAGE);
    }
    }//GEN-LAST:event_btncomprobanteActionPerformed
    private void gestionarExcepcion(Exception ex) {
        System.out.println("Error2: " + ex.getMessage());
        JOptionPane.showMessageDialog(null, "Error2: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }
    private void btnbpersona1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbpersona1ActionPerformed
        String dni = txtdni1.getText().trim();
        //CONSULTAR A API PARA PODER REGISTRARLO
        String url = null;// Obtener el texto y eliminar espacios en blanco

        if (!dni.isEmpty()) { // Verificar si el texto no está vacío
            PasajeroDAO pasajerodao = new PasajeroDAOimpl();
            PasajeroModel pasajero = pasajerodao.obtenerPasajeroPorDNI(dni);
            PasajeroModel psjemodel = new PasajeroModel();

            if (pasajero != null) {
                int pasajero_existe = pasajero.getIdPsje();
                System.out.println(pasajero_existe);
                txtpasajero1.setText(pasajero.getApePsje() + " " + pasajero.getNomPsje());
            } else {
                // No se encontró el pasajero, muestra un JOptionPane
                JOptionPane.showMessageDialog(null, "Pasajero no se encuentra en la Base de Datos Interna, se realizará una consulta externa. \n Espere por favor.", "Información", JOptionPane.INFORMATION_MESSAGE);

                //CONSULTAR A API PARA PODER REGISTRARLO
                url = apidao.obtenerApiPorId(1).getUrlApi() + dni;
                try {
                    Funciones.realizarConsultaApi(url);
                    json = Funciones.realizarConsultaApi(url);
                } catch (IOException ex) {
                    Logger.getLogger(Pasajes.class.getName()).log(Level.SEVERE, null, ex);
                }
                try {
                    System.out.println(Funciones.realizarConsultaApi(url));

                    // Crear un objeto Gson
                    Gson gson = new Gson();

                    // Analizar el JSON y convertirlo en un objeto JsonElement
                    JsonElement jsonElement = gson.fromJson(json, JsonElement.class);

                    // Obtener los valores deseados del JsonElement
                    String nombrecompleto = jsonElement.getAsJsonObject().get("nombre").getAsString();
                    String nombres = jsonElement.getAsJsonObject().get("nombres").getAsString();
                    String apellidos = jsonElement.getAsJsonObject().get("apellidoPaterno").getAsString() + " " + jsonElement.getAsJsonObject().get("apellidoMaterno").getAsString();
                    String numdoc = jsonElement.getAsJsonObject().get("numeroDocumento").getAsString();

                    txtpasajero1.setText(nombrecompleto);
                    psjemodel.setNumdocPsje(numdoc);
                    psjemodel.setNomPsje(nombres);
                    psjemodel.setApePsje(apellidos);

                    //AGREGAR PERSONA
                    pasajerodao.agregarPasajero(psjemodel);

                } catch (IOException ex) {
                    Logger.getLogger(Pasajes.class.getName()).log(Level.SEVERE, null, ex);
                }
            }

            System.out.println(url);
        } else {
            JOptionPane.showMessageDialog(null, "Ingrese un DNI de pasajero válido antes de consultar.", "ADVERTENCIA", JOptionPane.INFORMATION_MESSAGE);
            System.out.println("Ingrese un DNI de pasajero válido antes de consultar.");
        }
    }//GEN-LAST:event_btnbpersona1ActionPerformed

    private void btnnpasajero2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnpasajero2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnnpasajero2ActionPerformed

    private void limpiarCamposTexto(JTextField... camposTexto) {
        for (JTextField campo : camposTexto) {
            campo.setText("");
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnbempresa;
    private javax.swing.JButton btnbpersona;
    private javax.swing.JButton btnbpersona1;
    private javax.swing.JButton btncomprobante;
    private javax.swing.JButton btnnempresa;
    private javax.swing.JButton btnnpasajero;
    private javax.swing.JButton btnnpasajero1;
    private javax.swing.JButton btnnpasajero2;
    private javax.swing.JComboBox<String> cbunidad;
    private javax.swing.JCheckBox chkbfactura;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pnlfactura;
    private javax.swing.JTable tabenco;
    private javax.swing.JTextField txtcantidadenco;
    private javax.swing.JTextField txtcomprobante;
    private javax.swing.JTextField txtdescenco;
    private javax.swing.JTextField txtdestino;
    private javax.swing.JTextField txtdireccion;
    public static javax.swing.JTextField txtdni;
    public static javax.swing.JTextField txtdni1;
    private javax.swing.JTextField txtorigen;
    public static javax.swing.JTextField txtpasajero;
    public static javax.swing.JTextField txtpasajero1;
    private javax.swing.JTextField txtprecio;
    private javax.swing.JTextField txtrazon;
    private javax.swing.JTextField txtruc;
    private javax.swing.JTextField txttipocomprobante;
    // End of variables declaration//GEN-END:variables
}
