/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package sistemapasajes.View;

import java.awt.event.ActionEvent;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import sistemapasajes.Funciones;
import sistemapasajes.dao.RutaAsignadaDAO;
import sistemapasajes.dao.RutaAsignadaDAOImpl;
import sistemapasajes.dao.RutaDAO;
import sistemapasajes.dao.RutaDAOImpl;
import sistemapasajes.dao.VehiculoDAO;
import sistemapasajes.dao.VehiculoDAOImpl;
import sistemapasajes.modelo.AsignacionRutaModel;
import sistemapasajes.modelo.RutaModel;
import sistemapasajes.modelo.VehiculoModel;

/**
 *
 * @author edson
 */
public class ProgramacionDiaria extends javax.swing.JInternalFrame {

    List<RutaModel> listarutas;

    public ProgramacionDiaria() {
        initComponents();
        inicializarComboBoxRutas();
        cargarFechaActual();
        cargarDatosVehiculos();
    }

    private void inicializarComboBoxRutas() {
        cbruta.removeAllItems();
        RutaDAO rutadao = new RutaDAOImpl();
        listarutas = rutadao.obtenerTodasRutas();
        cbruta.addItem("Seleccionar");
        for (int i = 0; i < listarutas.size(); i++) {
            cbruta.addItem(listarutas.get(i).getTramoRuta());

        }
        // Agregar ActionListener que referencia a la función separada
        cbruta.addActionListener(this::obtenerRuta);
    }

    private void cargarFechaActual() {
        // Get the current date
        Date currentDate = Calendar.getInstance().getTime();

        // Set the current date to the JDateChooser
        jDateChooser1.setDate(currentDate);
    }
    
        private void obtenerRuta(ActionEvent e) {
        // Obtener la ruta seleccionada
        String rutaSeleccionada = (String) cbruta.getSelectedItem();

        // Buscar la ruta en la lista
        for (RutaModel ruta : listarutas) {
            if (ruta.getTramoRuta().equals(rutaSeleccionada)) {
                // Actualizar el precio en el JTextField
                
                txtorigen.setText(String.valueOf(ruta.getPunto1Ruta()));
                txtdestino.setText(String.valueOf(ruta.getPunto2Ruta()));
                break;  // No es necesario seguir buscando
            }
        }
    }

    private void cargarDatosVehiculos() {
        DefaultTableModel modeloTabla = new DefaultTableModel();
        modeloTabla.addColumn("ID");
        modeloTabla.addColumn("Descripción");
        modeloTabla.addColumn("Placa");
        modeloTabla.addColumn("N° de Asientos");
        modeloTabla.addColumn("Conductor");

        VehiculoDAO vehidao = new VehiculoDAOImpl();
        List<VehiculoModel> vehiculos = vehidao.obtenerTodosVehiculos();
        for (VehiculoModel vehiculo : vehiculos) {
            Object[] fila = {
                vehiculo.getIdVehi(),
                vehiculo.getDescVehi(),
                vehiculo.getPlacaVehi(),
                vehiculo.getNumVehi(),
                vehiculo.getCondVehi()
            };
            modeloTabla.addRow(fila);
        }
        // Establecer el modo de autoajuste para que las columnas se adapten al contenido
        tabvehi.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);

        tabvehi.setModel(modeloTabla);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cbruta = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabvehi = new javax.swing.JTable();
        btnguardar = new javax.swing.JButton();
        txtorigen = new javax.swing.JTextField();
        txtdestino = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        setClosable(true);
        setIconifiable(true);
        setTitle("Programación Diaria");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Ruta:");

        cbruta.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbruta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Fecha:");

        jDateChooser1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        tabvehi.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tabvehi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabvehi.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jScrollPane1.setViewportView(tabvehi);

        btnguardar.setBackground(new java.awt.Color(30, 200, 130));
        btnguardar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnguardar.setForeground(new java.awt.Color(255, 255, 255));
        btnguardar.setText("Guardar");
        btnguardar.setBorder(null);
        btnguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnguardarActionPerformed(evt);
            }
        });

        txtorigen.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtorigen.setEnabled(false);
        txtorigen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtorigenActionPerformed(evt);
            }
        });

        txtdestino.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtdestino.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtorigen, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtdestino, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(398, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnguardar, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbruta, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(cbruta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtorigen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtdestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnguardar, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnguardarActionPerformed

        try {
            // Obtener la ruta seleccionada del JComboBox
            int rutaSeleccionada = cbruta.getSelectedIndex();
            String descrutaSeleccionada = (String) cbruta.getSelectedItem();

            // Obtener las filas seleccionadas de la tabla
            int[] filasSeleccionadas = tabvehi.getSelectedRows();

            // Verificar si se ha seleccionado alguna fila y ruta
            if (filasSeleccionadas.length == 0 || "Seleccionar".equals(rutaSeleccionada)) {
                JOptionPane.showMessageDialog(this, "Seleccione al menos una fila y una ruta.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            // Obtener la fecha y hora actual
            Date fecha = jDateChooser1.getDate();
            String fechaFormato = Funciones.convertirFecha(fecha);

            Date hora = new Date();
            SimpleDateFormat horaFormato = new SimpleDateFormat("HH:mm:ss");
            String horaTexto = horaFormato.format(hora);

            // Crear instancia de AsignacionRutaModel y establecer valores
            RutaAsignadaDAO rutaAsignadaDao = new RutaAsignadaDAOImpl();

            for (int filaSeleccionada : filasSeleccionadas) {
                // Obtener el ID de asignación de ruta desde la tabla
                int idvehiculo = Integer.parseInt(tabvehi.getValueAt(filaSeleccionada, 0).toString());

                AsignacionRutaModel asignacionruta = new AsignacionRutaModel();
                
                asignacionruta.setFechaAsigRuta(fechaFormato);
                asignacionruta.setHoraAsigRuta(horaTexto);
                asignacionruta.setVehiculoAsigRuta(idvehiculo);
                asignacionruta.setRutaAsigRuta(rutaSeleccionada);
                asignacionruta.setOrigenAsigRuta(txtorigen.getText());
                asignacionruta.setDestinoAsigRuta(txtdestino.getText());

                //JOptionPane.showMessageDialog(this, "ID VEHICULO: " + idvehiculo + "- " + rutaSeleccionada, "Éxito", JOptionPane.INFORMATION_MESSAGE);

                // Guardar en la base de datos
                rutaAsignadaDao.agregarRutaAsignada(asignacionruta);
                
            }

            // Limpiar la selección en la tabla y el JComboBox
            tabvehi.clearSelection();
            cbruta.setSelectedIndex(0);

            // Actualizar la tabla con los datos actualizados de la base de datos (si es necesario)
            cargarDatosVehiculos();

            //JOptionPane.showMessageDialog(this, "Datos guardados exitosamente.", "Éxito", JOptionPane.INFORMATION_MESSAGE);

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error al guardar los datos. Consulta el registro de la aplicación para más detalles.", "Error", JOptionPane.ERROR_MESSAGE);
        }


    }//GEN-LAST:event_btnguardarActionPerformed

    private void txtorigenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtorigenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtorigenActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnguardar;
    private javax.swing.JComboBox<String> cbruta;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabvehi;
    private javax.swing.JTextField txtdestino;
    private javax.swing.JTextField txtorigen;
    // End of variables declaration//GEN-END:variables
}
